apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: kasten-nfs
   namespace: kasten-io
spec:
   storageClassName: nfs-client
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 10Gi

