apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loft.techlabenterprise.com
  namespace: default
spec:
  secretName: loft.techlabenterprises.tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: loft.techlabenterprises.com
  dnsNames:
    - loft.techlabenterprises.com

