apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn.techlabenterprise.com
  namespace: default
spec:
  secretName: longhorn.techlabenterprises.tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: longhorn.techlabenterprises.com
  dnsNames:
    - longhorn.techlabenterprises.com

