apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techlabenterprises.com
  namespace: default
spec:
  secretName: techlabenterprises.com.tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: techlabenterprises.com
  dnsNames:
    - techlabenterprises.com
