apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: urbanbaby.co.ke
  namespace: default
spec:
  secretName: urbanbaby.co.ke.tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: urbanbaby.co.ke
  dnsNames:
    - urbanbaby.co.ke

