apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: odoo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: odoo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: odoo
    spec:
      containers:
      - image: odoo:latest
        name: odoo
        env:
        - name: HOST
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
        - name: PORT
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
        - name: USER
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
        - name: PASSWORD
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
