# Use v1 as an example
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
  name: longhorn
driver: driver.longhorn.io
deletionPolicy: Delete
