kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudflare-apikey-secret
  # IMPORTANT: secret must be in same namespace as Cert Manager deployment
  namespace: cert-manager
stringData:
  # AWS Secret Access Key generated for our user
  secret-access-key: 2102a1fe2099caa83a80418b4ca7e4626f3f8
  # No need to specify Access Key ID here
  # It'll be specified on Cert Manager Issuer resource
